sl: add architecture into xml

diff --git a/sl/check-property.sh.in b/sl/check-property.sh.in
--- a/sl/check-property.sh.in
+++ b/sl/check-property.sh.in
@@ -96,6 +96,10 @@ EOF
 }
 
 PRP_FILE=
+DEPTH=""
+XMLTRACE=""
+SRC_FILE=
+ARCH=
 
 # write trace to stderr by default
 TRACE="/dev/fd/2"
@@ -114,7 +118,7 @@ fi
 
 eval set -- $ARGS
 
-while true; do
+while [ $# -gt 0 ]; do
   case "$1" in
     -p|--propertyfile)
       PRP_FILE="$2"; shift 2;;
@@ -123,11 +127,17 @@ while true; do
     -v|--verbose)
       export VERBOSE="yes"; shift;;
     --)
-      shift; break;;
+      SRC_FILE="$2"; shift 2; CFLAGS="$@";;
+    -m32)
+      ARCH="32"; break;;
+    -m64)
+      ARCH="64"; break;;
+    *)
+      shift;;
   esac
 done
 
-test -r "$1" || usage
+test -r "$SRC_FILE" || usage
 test -r "$PRP_FILE" || usage
 
 # classify the property to be verified
@@ -199,8 +209,114 @@ report_unsafe() {
     if test -z "$PROPERTY"; then
         report_result "FALSE" "" "$2"
     else
-        report_result "FALSE" "($PROPERTY)" "$2"
+      # set property in XML trace
+      SPEC=`grep $PROPERTY $PRP_FILE`
+      report_result "FALSE" "($PROPERTY)" "$2"
     fi
+
+    # change witness XML
+    HASH=`(sha1sum "$SRC_FILE" | sed 's/ .*//')`
+
+    if test -z "$HASH"; then
+      printf "%s: error: failed to generate hash for: %s\n" "$SELF" \
+        "$SRC_FILE" >&2
+    fi
+
+    if test -z "$SPEC"; then
+      printf "%s: error: failed to generate specification from: %s\n" "$SELF" \
+        "$PRP_FILE" >&2
+    fi
+
+    sed -i s/__SRCFILEHASH__/"${HASH}"/ "$XMLTRACE"
+    sed -i s/__SPECIFICATION__/"${SPEC}"/ "$XMLTRACE"
+    sed -i s/__ARCHITECTURE__/"${ARCH}bit"/ "$XMLTRACE"
+
+    exit 0
+}
+
+report_safe() {
+#    PROPERTY="$1"
+
+    report_result "TRUE" "" "$2"
+    # generate correctness witness with all properties
+    SPEC=`cat "$PRP_FILE"`
+    HASH=`(sha1sum "$SRC_FILE" | sed 's/ .*//')`
+
+    if test -z "$HASH"; then
+      printf "%s: error: failed to generate hash for: %s\n" "$SELF" \
+        "$SRC_FILE" >&2
+    fi
+
+    if test -z "$SPEC"; then
+      printf "%s: error: failed to generate specification from: %s\n" "$SELF" \
+        "$PRP_FILE" >&2
+    fi
+
+    # graph with one start node
+    echo -e "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n\
+<graphml xmlns=\"http://graphml.graphdrawing.org/xmlns\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n\
+\t<key attr.name=\"originFileName\" attr.type=\"string\" for=\"edge\" id=\"originfile\">\n\
+\t\t<default>\"&lt;command-line&gt;\"</default>\n\
+\t</key>\n\
+\t<key attr.name=\"invariant\" attr.type=\"string\" for=\"node\" id=\"invariant\"/>\n\
+\t<key attr.name=\"invariant.scope\" attr.type=\"string\" for=\"node\" id=\"invariant.scope\"/>\n\
+\t<key attr.name=\"namedValue\" attr.type=\"string\" for=\"node\" id=\"named\"/>\n\
+\t<key attr.name=\"nodeType\" attr.type=\"string\" for=\"node\" id=\"nodetype\">\n\
+\t\t<default>path</default>\n\
+\t</key>\n\
+\t<key attr.name=\"isFrontierNode\" attr.type=\"boolean\" for=\"node\" id=\"frontier\">\n\
+\t\t<default>false</default>\n\
+\t</key>\n\
+\t<key attr.name=\"isViolationNode\" attr.type=\"boolean\" for=\"node\" id=\"violation\">\n\
+\t\t<default>false</default>\n\
+\t</key>\n\
+\t<key attr.name=\"isEntryNode\" attr.type=\"boolean\" for=\"node\" id=\"entry\">\n\
+\t\t<default>false</default>\n\
+\t</key>\n\
+\t<key attr.name=\"isSinkNode\" attr.type=\"boolean\" for=\"node\" id=\"sink\">\n\
+\t\t<default>false</default>\n\
+\t</key>\n\
+\t<key attr.name=\"enterLoopHead\" attr.type=\"boolean\" for=\"edge\" id=\"enterLoopHead\">\n\
+\t\t<default>false</default>\n\
+\t</key>\n\
+\t<key attr.name=\"violatedProperty\" attr.type=\"string\" for=\"node\" id=\"violatedProperty\"/>\n\
+\t<key attr.name=\"threadId\" attr.type=\"string\" for=\"edge\" id=\"threadId\"/>\n\
+\t<key attr.name=\"sourcecodeLanguage\" attr.type=\"string\" for=\"graph\" id=\"sourcecodelang\"/>\n\
+\t<key attr.name=\"programFile\" attr.type=\"string\" for=\"graph\" id=\"programfile\"/>\n\
+\t<key attr.name=\"programHash\" attr.type=\"string\" for=\"graph\" id=\"programhash\"/>\n\
+\t<key attr.name=\"specification\" attr.type=\"string\" for=\"graph\" id=\"specification\"/>\n\
+\t<key attr.name=\"memoryModel\" attr.type=\"string\" for=\"graph\" id=\"memorymodel\"/>\n\
+\t<key attr.name=\"architecture\" attr.type=\"string\" for=\"graph\" id=\"architecture\"/>\n\
+\t<key attr.name=\"producer\" attr.type=\"string\" for=\"graph\" id=\"producer\"/>\n\
+\t<key attr.name=\"sourcecode\" attr.type=\"string\" for=\"edge\" id=\"sourcecode\"/>\n\
+\t<key attr.name=\"startline\" attr.type=\"int\" for=\"edge\" id=\"startline\"/>\n\
+\t<key attr.name=\"startoffset\" attr.type=\"int\" for=\"edge\" id=\"startoffset\"/>\n\
+\t<key attr.name=\"lineColSet\" attr.type=\"string\" for=\"edge\" id=\"lineCols\"/>\n\
+\t<key attr.name=\"control\" attr.type=\"string\" for=\"edge\" id=\"control\"/>\n\
+\t<key attr.name=\"assumption\" attr.type=\"string\" for=\"edge\" id=\"assumption\"/>\n\
+\t<key attr.name=\"assumption.resultfunction\" attr.type=\"string\" for=\"edge\" id=\"assumption.resultfunction\"/>\n\
+\t<key attr.name=\"assumption.scope\" attr.type=\"string\" for=\"edge\" id=\"assumption.scope\"/>\n\
+\t<key attr.name=\"enterFunction\" attr.type=\"string\" for=\"edge\" id=\"enterFunction\"/>\n\
+\t<key attr.name=\"returnFromFunction\" attr.type=\"string\" for=\"edge\" id=\"returnFrom\"/>\n\
+\t<key attr.name=\"predecessor\" attr.type=\"string\" for=\"edge\" id=\"predecessor\"/>\n\
+\t<key attr.name=\"successor\" attr.type=\"string\" for=\"edge\" id=\"successor\"/>\n\
+\t<key attr.name=\"witness-type\" attr.type=\"string\" for=\"graph\" id=\"witness-type\"/>\n\
+\n\
+<graph edgedefault=\"directed\">\n\
+\t<data key=\"sourcecodelang\">C</data>\n\
+\t<data key=\"producer\">PredatorHP</data>\n\
+\t<data key=\"specification\">${SPEC}</data>\n\
+\t<data key=\"programhash\">${HASH}</data>\n\
+\t<data key=\"memorymodel\">precise</data>\n\
+\t<data key=\"architecture\">${ARCH}bit</data>\n\
+\t<data key=\"programfile\">${SRC_FILE}</data>\n\
+\t<data key=\"witness-type\">correctness_witness</data>\n\
+\t<node id=\"A1\">\n\
+\t\t<data key=\"entry\">true</data>\n\
+\t</node>\n\
+</graph>\n\
+</graphml>" > "$XMLTRACE"
+
     exit 0
 }
 
@@ -306,6 +422,10 @@ elif match "$TASK" "memtrack"; then
     ARGS="no_error_recovery,memleak_is_error"
 elif match "$TASK" "deref" || match "$TASK" "free" || match "$TASK" "overflow"; then
     ARGS="no_error_recovery"
+fi
+
+if test ! x = "x$XMLTRACE"; then
+    ARGS="$ARGS,xml_trace:$XMLTRACE"
 fi
 
 if [ -z $ENABLE_LLVM ]; then
